"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-b579z17on8aia7)68+l4$e*&fj$+-(xh)2m5$l))c1l_dpbd7$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'daphne',
    'jazzmin', # Must be before admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'channels',
    
    'users.apps.UsersConfig',
    'medical.apps.MedicalConfig',
    'ai_agent.apps.AiAgentConfig',
    'pharmacy.apps.PharmacyConfig',
    'lab.apps.LabConfig',
    'billing.apps.BillingConfig',
    
    # Security
    'axes',
    'csp',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'csp.middleware.CSPMiddleware', # CSP
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware', # Axes for Rate Limiting/Brute Force
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

# ... (Templates, WSGI, Database remain same) ...

# --- SECURITY ENHANCEMENTS ---

# 1. Brute Force Protection (Axes)
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = 1 # hour
AXES_LOCKOUT_TEMPLATE = "403.html" # Simple fallback
AXES_RESET_ON_SUCCESS = True

# 2. Content Security Policy (CSP)
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ["'self'"],
        "style-src": ["'self'", "'unsafe-inline'", "cdn.jsdelivr.net", "fonts.googleapis.com", "cdnjs.cloudflare.com"],
        "script-src": ["'self'", "'unsafe-inline'", "cdn.jsdelivr.net", "cdnjs.cloudflare.com"],
        "img-src": ["'self'", "data:", "cdn.jsdelivr.net"],
        "font-src": ["'self'", "fonts.gstatic.com", "cdnjs.cloudflare.com"],
    }
}

# 3. Secure Headers (Production Ready)
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'
# CSRF_COOKIE_SECURE = True # Enable in Prod (Requires HTTPS)
# SESSION_COOKIE_SECURE = True # Enable in Prod (Requires HTTPS)

# 4. Password Validation (Existing is good, ensuring strong default)
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator', 'OPTIONS': {'min_length': 10}}, # Enforce 10 chars
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ... (Rest of settings) ...

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

ASGI_APPLICATION = 'config.asgi.application'

AUTH_USER_MODEL = 'users.User'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend', # Axes
    'django.contrib.auth.backends.ModelBackend', # Default
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

CORS_ALLOW_ALL_ORIGINS = True

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

import os
DEEPSEEK_API_KEY = os.environ.get("DEEPSEEK_API_KEY", "sk-mock-key")

JAZZMIN_SETTINGS = {
    "site_title": "Aarogya Access",
    "site_header": "Aarogya HMS",
    "site_brand": "Aarogya",
    "welcome_sign": "Welcome to Aarogya Health System",
    "copyright": "Aarogya Ltd",
    "search_model": ["users.User", "medical.Patient"],
    
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "AI Insights", "url": "/api/ai/analyze/", "new_window": True},
    ],

    "icons": {
        "users.User": "fas fa-user-shield",
        "users.Doctor": "fas fa-user-md",
        "users.Patient": "fas fa-procedures",
        "users.Department": "fas fa-hospital-alt",
        
        "medical.Appointment": "fas fa-calendar-check",
        "medical.Vitals": "fas fa-heartbeat",
        "medical.MedicalHistory": "fas fa-notes-medical",
        
        "ai_agent.AIAnalysis": "fas fa-brain",
        
        "pharmacy.Medicine": "fas fa-pills",
        "pharmacy.Prescription": "fas fa-file-prescription",
        
        "lab.LabTest": "fas fa-microscope",
        "lab.TestResult": "fas fa-vial",
        
        "billing.Invoice": "fas fa-file-invoice-dollar",
    },
    "order_with_respect_to": [
        "users", 
        "medical", 
        "pharmacy", 
        "lab", 
        "billing", 
        "ai_agent", 
        "auth"
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "theme": "cerulean", # Blue theme
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}
